# example config for a python project
default_stages: [commit]
repos:
  - repo: https://github.com/myint/autoflake
    rev: b330072a26
    hooks:
      - id: autoflake
        args: [-i, --remove-all-unused-imports, --ignore-init-module-imports]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.1.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.3
#    hooks:
#      - id: flake8
#        additional_dependencies: [flake8-docstrings, flake8-bugbear]
