# example config for a python project
default_stages: [commit]
repos:
  - repo: https://github.com/bschiela/githooks
    rev: 19b1347
    hooks:
      - id: do-not-commit
      - id: python-unittest
        stages: [push]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args: [-i, --remove-all-unused-imports, --ignore-init-module-imports]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
